# Filters / settings
price_min: 5.0
volume_mult: 1.5         # current bar vol must be >= 1.5 x avg(20)
rsi_period: 14
ema_fast: 20
ema_slow: 50
timeframe: 5Min
feed: iex                 # free tier on Alpaca ('sip' if you have that plan)
universe_limit: 100
# Session (RTH) for labeling only (signal runs extended by default)
regular_hours:
  tz: America/New_York
  start: "09:30"
  end:   "16:00"

# Webhook (optional): Slack/Discord or any JSON POST endpoint
webhook_url: ""          # e.g., https://hooks.slack.com/services/XXX
webhook_type: "slack"    # "slack" or "discord" or "generic"
