# -------- Data / timeframes --------
feed: "iex"                 # "iex" or "sip" depending on your plan
timeframe: "5Min"           # working TF (catches crosses sooner)
confirm_timeframe: "15Min"  # slower TF slope confirm

# -------- Core indicators --------
ema_fast: 20
ema_slow: 50
rsi_period: 14
adx_period: 14
adx_min: 18                 # looser than 22 — admit weaker-but-building trends

# -------- Price/volume gates --------
price_min: 3.0              # allow more liquid mid-caps and small caps
volume_mult: 0.8            # was 1.2; looser to avoid filtering out low-spike bars

# -------- Universe (wider, then filter) --------
universe_exchanges: ["NYSE","NASDAQ","AMEX"]
universe_limit: 3000        # initial pull (script multiplies by 3 for ranking input)
universe_top_n: 800         # keep top by intraday $ volume before RVOL

# -------- RVOL --------
rvol_min: 1.2               # was 1.5; easier entry, still weeds out dead tickers
rvol_lookback_days: 30
rvol_use_same_weekday: true # normalize for weekday volume patterns

# -------- Signal logic --------
signal_lookback_hours: 8    # longer lookback if last_run.json missing
allow_persistent: true      # fire once/day if state still valid, even w/o new cross
bull_rsi_min: 52            # slightly above neutral
bear_rsi_max: 48            # slightly below neutral
min_score: 1.8              # was 2.0; lets borderline setups through
ranking_min_score: 1.6      # was 1.75; keep top lists populated
max_alerts_per_run: 25
dedupe_window_days: 5

# -------- Regular hours --------
regular_hours:
  start: "09:30"
  end:   "16:00"
  tz:    "America/New_York"

# -------- Output / Webhook --------
signals_csv: "data/signals.csv"
webhook_type: "discord"     # slack | discord | generic
webhook_url: ""             # or set via env

# -------- Health / telemetry --------
health:
  enabled: true
  min_universe: 50                 # after RVOL filter
  min_symbols_with_bars: 30
  min_bar_coverage_pct: 60         # % of universe that returned >=1 bar
  warn_on_empty_signals: true      # send a friendly "no signals" note

stats_report:
  enabled: true
  level: "compact"                 # compact | verbose

# -------- Optional ranking alert (top lists every run) --------
ranking_alert:
  enabled: true
  top_n: 10
