# -------- Data / timeframes --------
feed: "iex"                  # "iex" or "sip"
timeframe: "1Min"            # faster working TF for earlier pings
confirm_timeframe: "5Min"    # slower TF slope confirm (filters noise)

# -------- Core indicators --------
ema_fast: 20
ema_slow: 50
rsi_period: 14
adx_period: 14
adx_min: 18                  # loose by default

# -------- Price/volume gates --------
price_min: 3.0
volume_mult: 0.8

# -------- Universe (wide, then filter) --------
universe_exchanges: ["NYSE","NASDAQ","AMEX"]
universe_limit: 3000
universe_top_n: 800

# -------- RVOL --------
rvol_min: 1.2
rvol_lookback_days: 30
rvol_use_same_weekday: true

# -------- Early / predictive-ish signals --------
early_alerts_max: 30  # cap early heads-up alerts per run

near_cross:
  enabled: true
  eps_pct: 0.002       # within 0.2% of spread=0
  lookback: 3
  adx_rising: true
  rsi_floor_bull: 48
  rsi_ceiling_bear: 52

macd_early:
  enabled: true
  lookback: 3
  adx_rising: true
  rsi_floor_bull: 48
  rsi_ceiling_bear: 52
  macd_fast: 12       # (used by code defaults too)
  macd_slow: 26
  macd_signal: 9

rsi_regime:
  enabled: true
  lookback: 3
  adx_rising: true
  bull_threshold: 60   # crossing above for bulls
  bear_threshold: 40   # crossing below for bears

vwap_reclaim:
  enabled: true
  lookback: 3          # require last N bars were on the other side
  vol_spike_mult: 1.2  # bar volume vs 20-bar avg
  adx_rising: true

squeeze_breakout:
  enabled: true
  lookback: 5
  min_width: 0.02      # “tight” band width threshold
  adx_rising: true
  bb_period: 20
  bb_k: 2.0

# -------- Signal logic (classic crosses & rankings) --------
signal_lookback_hours: 8
allow_persistent: true
bull_rsi_min: 52
bear_rsi_max: 48
min_score: 1.8
ranking_min_score: 1.6
max_alerts_per_run: 25
dedupe_window_days: 5

# -------- Regular hours --------
regular_hours:
  start: "09:30"
  end:   "16:00"
  tz:    "America/New_York"

# -------- Output / Webhook --------
signals_csv: "data/signals.csv"
webhook_type: "discord"
webhook_url: ""

# -------- Health / telemetry --------
health:
  enabled: true
  min_universe: 50
  min_symbols_with_bars: 30
  min_bar_coverage_pct: 60
  warn_on_empty_signals: true

stats_report:
  enabled: true
  level: "compact"

# -------- Ranking snapshot --------
ranking_alert:
  enabled: true
  top_n: 10
