name: NYSE 20/50 EMA Monitor

on:
  workflow_dispatch: {}
  schedule:
    # Every 15 minutes, 24/7 (UTC)
    - cron: "*/15 * * * *"
    # Daily summary at ~23:59 CT (≈ 04:59 UTC)
    - cron: "59 4 * * *"
    # Weekly roll-up Sunday 23:59 CT (≈ Monday 04:59 UTC)
    - cron: "59 4 * * MON"

permissions:
  contents: write

jobs:
  monitor:
    if: github.event.schedule == '*/15 * * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install -r requirements.txt
      - name: Run monitor
        env:
          ALPACA_KEY_ID: ${{ secrets.ALPACA_KEY_ID }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        run: |
          python monitor.py
      - name: Commit logs/artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv data/*.json artifacts/* 2>/dev/null || true
          git diff --cached --quiet || (git commit -m "Update signals/artifacts" && git push)

  summary-daily:
    if: github.event.schedule == '59 4 * * *'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install -r requirements.txt
      - name: Daily summary
        run: python summary.py daily

  summary-weekly:
    if: github.event.schedule == '59 4 * * MON'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install -r requirements.txt
      - name: Weekly summary
        run: python summary.py weekly
