name: NYSE 20/50 EMA Monitor

on:
  workflow_dispatch: {}
  schedule:
    # Every 15 minutes, 24/7 (UTC)
    - cron: "*/15 * * * *"
    # Daily summary at ~23:59 CT (≈ 04:59 UTC)
    - cron: "59 4 * * *"
    # Weekly roll-up Sunday 23:59 CT (≈ Monday 04:59 UTC)
    - cron: "59 4 * * MON"

permissions:
  contents: write

# Prevent overlapping runs of the same workflow/branch
concurrency:
  group: nyse-ema-monitor-${{ github.ref }}
  cancel-in-progress: false

jobs:
  monitor:
    if: github.event.schedule == '*/15 * * * *' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt

      # Uses 'shell: python' so we avoid bash heredoc pitfalls.
      - name: Test Discord webhook (optional)
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        shell: python
        run: |
          import os, requests, sys
          url = os.environ.get("WEBHOOK_URL", "")
          if not url:
              print("No WEBHOOK_URL secret set; skipping test.")
              sys.exit(0)
          try:
              r = requests.post(url, json={"content":"✅ Test from GitHub Actions (no trading signal)."}, timeout=10)
              r.raise_for_status()
              print("Posted test:", r.status_code)
          except Exception as e:
              print("Webhook test failed:", e)

      - name: Smoke test (manual only)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          ALPACA_KEY_ID: ${{ secrets.ALPACA_KEY_ID }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          ALPACA_ENV: ${{ vars.ALPACA_ENV }}
          VERBOSE: "1"
        run: |
          python monitor.py --tickers IBM,KO,XOM --dry-run

      - name: Run monitor
        env:
          ALPACA_KEY_ID: ${{ secrets.ALPACA_KEY_ID }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          ALPACA_ENV: ${{ vars.ALPACA_ENV }}       # 'paper' or 'live'
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_TYPE: discord
        run: |
          python monitor.py

      - name: Commit logs/artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv data/*.json artifacts/* 2>/dev/null || true
          git diff --cached --quiet || (git commit -m "Update signals/artifacts" && git push)

  summary-daily:
    if: github.event.schedule == '59 4 * * *'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt

      - name: Daily summary
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_TYPE: discord
        run: python summary.py daily

  summary-weekly:
    if: github.event.schedule == '59 4 * * MON'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt

      - name: Weekly summary
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          WEBHOOK_TYPE: discord
        run: python summary.py weekly
